### PR TITLE
Added RSpec tests

### PR DESCRIPTION
**Pull request by Zrp200**
- Added RSpec dependencies
- Added Gemfile

### CODE REVIEW

**Comment by Zrp200** [comment]
Do you want RSpec tests or Unit::Test tests?

**Comment by martimatix** [comment]
I don't have experience with either. Which one do you prefer?

**Comment by Zrp200** [comment]
RSpec, since I find it easier to use and learn

**Comment by martimatix** [comment]
Let's go with RSpec.

**Comment by martimatix** [comment]
I spent the entire evening trying to install rspecs and finally succeeded. It was worth the turmoil since I learned about rvm. It's getting late here so I haven't had a chance to play with rspec but I do plan to contribute to the testing.

**Comment by Zrp200** [comment]
That would be great.

**Pull request merged**
